"""Stream name constants for Redis messaging."""

QUOTE_STREAM = "dreambot:quotes"
AGG_STREAM = "dreambot:agg1s"
OPTION_META_STREAM = "dreambot:option_meta"
FEATURE_STREAM = "dreambot:features"
SIGNAL_STREAM = "dreambot:signals"
RISK_ORDER_STREAM = "dreambot:risk_orders"
RISK_COMMAND_STREAM = "dreambot:risk_commands"
OMS_ORDER_STREAM = "dreambot:oms_orders"
EXECUTION_STREAM = "dreambot:execution_reports"
INGEST_HEARTBEAT_STREAM = "dreambot:ingest_heartbeat"
OMS_METRIC_STREAM = "dreambot:oms_metrics"
PORTFOLIO_STREAM = "dreambot:portfolio"
LEARNER_ADJUSTMENT_STREAM = "dreambot:learner_adjustments"
LEARNER_REWARD_STREAM = "dreambot:learner_rewards"
